// Code generated by cmd/gen-fit-schema. DO NOT EDIT.
//
// The source of truth is internal/fitschema. Regenerate with: just gen-fit-schema

/** optimizer.ParseMetric's vocabulary: the three composite profiles, then the single-term legacy metrics. */
export const METRIC_NAMES = [
  "balanced",
  "placement",
  "polish",
  "rms",
  "log",
  "spectral",
] as const;

/** Derived from METRIC_NAMES. */
export type MetricName = (typeof METRIC_NAMES)[number];

/** selectOptimizer's vocabulary. */
export const OPTIMIZER_NAMES = ["simple", "mayfly", "cmaes"] as const;

/** Derived from OPTIMIZER_NAMES. */
export type OptimizerName = (typeof OPTIMIZER_NAMES)[number];

/** CMAESOptimizer.resolve's vocabulary: the covariance it learns. */
export const CMAES_COVARIANCES = ["separable", "block"] as const;

/** Derived from CMAES_COVARIANCES. */
export type CmaesCovariance = (typeof CMAES_COVARIANCES)[number];

/** MayflyOptimizer.Validate's vocabulary. */
export const MAYFLY_VARIANTS = [
  "ma",
  "desma",
  "olce",
  "eobbma",
  "gsasma",
  "hmma",
  "mpma",
  "aoblmoa",
] as const;

/** Derived from MAYFLY_VARIANTS. */
export type MayflyVariant = (typeof MAYFLY_VARIANTS)[number];

/** mayfly.ConfigPreset's vocabulary, from config_loader.go upstream. A preset already chooses a dialect, so the engine refuses a preset and an explicit variant together; the form sends one or the other, never both. */
export const MAYFLY_PRESETS = [
  "unimodal",
  "multimodal",
  "highly_multimodal",
  "deceptive",
  "narrow_valley",
  "high_dimensional",
  "fast_convergence",
  "stable_convergence",
  "multi_objective",
] as const;

/** Derived from MAYFLY_PRESETS. */
export type MayflyPreset = (typeof MAYFLY_PRESETS)[number];

/** The `selection` knob's vocabulary: how crossover pairs its parents. */
export const MAYFLY_SELECTIONS = ["rank", "tournament"] as const;

/** Derived from MAYFLY_SELECTIONS. */
export type MayflySelection = (typeof MAYFLY_SELECTIONS)[number];

/**
 * The server's own limits, from internal/fitschema. They are mirrored here
 * so a value that cannot be accepted is refused before it is uploaded, not
 * after.
 */
export const FIT_LIMITS = {
  maxReferenceBytes: 16777216,
  note: { min: 0, max: 127 },
  velocity: { min: 0, max: 127 },
  maxIterations: { min: 1, max: 100000 },
  timeBudgetSeconds: { min: 0, max: 3600 },
  reportEvery: { min: 0, max: 100000 },
  mayflyPopulation: { min: 2, max: 4096 },
  mayflyEpochs: { min: 1, max: 1000 },
  mayflyRestarts: { min: 0, max: 1000 },
  mayflyStagnation: { min: 0, max: 100000 },
  mayflyTargetCost: { min: -1000000000000, max: 1000000000000 },
  mayflyNc: { min: -1, max: 4096 },
  mayflyNcRatio: { min: 0, max: 4096 },
  cmaesLambda: { min: 0, max: 4096 },
  cmaesSigma: { min: 0, max: 1 },
  cmaesSeed: { min: Number.MIN_SAFE_INTEGER, max: Number.MAX_SAFE_INTEGER },
  cmaesRestarts: { min: 0, max: 1000 },
  renderSeconds: { min: 0, max: 60 },
} as const;

/**
 * defaultFitRequest's values, from internal/fitschema, so a preset fitted
 * from the browser and one fitted from the terminal are the same fit.
 */
export const DEFAULT_FIT_REQUEST = {
  note: 69,
  velocity: 100,
  optimizer: "simple",
  metric: "balanced",
  maxIterations: 100,
  timeBudget: "30s",
  reportEvery: 10,
  align: true,
  normalizeGain: false,
  mayflyVariant: "desma",
  mayflyPopulation: 10,
  mayflySeed: "1",
  mayflyPreset: "",
  mayflyEpochs: 1,
  mayflyRestarts: 0,
  mayflyStagnation: 0,
  mayflySelection: "",
  cmaesCovariance: "separable",
  cmaesLambda: 0,
  cmaesSigma: 0.3,
  cmaesSeed: 0,
  cmaesRestarts: 0,
} as const;

/** The keys a bounds document may carry, in the order the docs list them. */
export const BOUNDS_KEYS = [
  "input_mix",
  "filter_freq",
  "amplitude",
  "frequency",
  "decay_ms",
  "harmonic_gain",
] as const;

/**
 * The dimensions the codec log-encodes. Their bounds must stay strictly
 * above zero: log(0) is not a number the unit-cube encoding can take, and
 * the server answers a non-positive one with a 400.
 */
export const LOG_ENCODED_BOUNDS_KEYS = [
  "filter_freq",
  "frequency",
  "decay_ms",
] as const;

/** The range model.ValidateBarParams holds each dimension to. DecodeParamBounds in internal/optimizer/boundsfile.go rejects a supplied range that leaves this box, and for a good reason: every candidate drawn from it would fail validation and score +Inf, so the fit would burn its whole budget to produce nothing. */
export const MODEL_BOUNDS_LIMITS = {
  input_mix: [0, 2] as const,
  filter_freq: [20, 20000] as const,
  amplitude: [-2, 2] as const,
  frequency: [0.01, 50000] as const,
  decay_ms: [0.1, 5000] as const,
  harmonic_gain: [0, 2] as const,
} as const;

/** optimizer.DefaultParamBounds, shown as the placeholder for each field. Two of these are narrowed per fit before the search starts, without a document: frequency to half the reference's fundamental up to 0.45 of its sample rate, and decay_ms to what a preset at the starting preset's note may carry. A document replaces the whole box, so a frequency key in one is the box that runs. */
export const DEFAULT_PARAM_BOUNDS = {
  input_mix: [0, 2] as const,
  filter_freq: [20, 20000] as const,
  amplitude: [-2, 2] as const,
  frequency: [20, 20000] as const,
  decay_ms: [0.5, 2000] as const,
  harmonic_gain: [0, 2] as const,
} as const;

/**
 * The progress cadence a Mayfly fit gets when nobody chooses one, mirroring
 * fitschema.DefaultMayflyReportEvery.
 *
 * A Mayfly iteration is a whole generation -- population, offspring, mutants
 * and elites, measured at roughly 47.7 objective evaluations at a population
 * of ten -- while a simple iteration is about one evaluation. The simple
 * backend's own default cadence would therefore mean "after roughly five
 * hundred renders" for Mayfly, long enough that a default time budget ends
 * before the first report and the cost curve stays empty for the whole run.
 */
export const MAYFLY_DEFAULT_REPORT_EVERY = 1;
