// Code generated by cmd/gen-presets. DO NOT EDIT.
//
// The source of truth is the JSON documents in assets/presets, read through
// assets.List. Regenerate with: just gen-presets

/** One built-in sound the engine can play. */
export interface SoundPreset {
  /** What the engine resolves the sound by: the document's filename stem. */
  readonly id: string;
  /** The document's own "name" field, which is what a picker shows. */
  readonly label: string;
  /** The MIDI note the preset was authored at. */
  readonly note: number;
}

export const SOUND_PRESETS: readonly SoundPreset[] = [
  { id: "default", label: "Default Glockenspiel", note: 69 },
  { id: "recorded-bar", label: "Recorded Bar", note: 69 },
] as const;

/**
 * The sound the engine falls back to, and what the picker starts on. It is the
 * same fallback assets.Preset applies to an empty id, so the two ends of the
 * bridge cannot disagree about which sound "none chosen" means.
 */
export const DEFAULT_SOUND_PRESET_ID = "default";
