// Command gen-presets writes the TypeScript mirror of the built-in sound list.
//
// The list exists once, as the JSON documents in assets/presets, and the
// browser needs it to render the Play tab's sound picker. Neither of the two
// obvious ways of getting it there works, for the same reasons the Mayfly
// tuning table is generated: serving it from the API is dead on GitHub Pages,
// which is exactly where the WASM path runs, and exporting it from the WASM
// module is too late, because the deck renders long before the module loads --
// a picker fed from the engine would be empty on first paint and empty in the
// visual baselines.
//
// So it is generated, and CI regenerates it and fails on a diff, exactly as
// cmd/gen-mayfly-tuning does.
//
// Usage:
//
//	go run ./cmd/gen-presets            # write the file
//	go run ./cmd/gen-presets --check    # fail if it is out of date
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/cwbudde/algo-glockenspiel/assets"
)

const typescriptPath = "web/src/api/presets.generated.ts"

func main() {
	check := flag.Bool("check", false, "verify the generated file is up to date instead of writing it")

	flag.Parse()

	generated, err := render()
	if err != nil {
		fail(err)
	}

	if err := emit(typescriptPath, generated, *check); err != nil {
		fail(err)
	}
}

func emit(path string, generated []byte, check bool) error {
	if !check {
		return os.WriteFile(path, generated, 0o644) //nolint:gosec // generated source, not a secret
	}

	current, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("%w: run `just gen-presets`", err)
	}

	if !bytes.Equal(current, generated) {
		return fmt.Errorf("%s is out of date: run `just gen-presets`", path)
	}

	return nil
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "gen-presets: %v\n", err)
	os.Exit(1)
}

func render() ([]byte, error) {
	listed, err := assets.List()
	if err != nil {
		return nil, err
	}

	var b strings.Builder

	b.WriteString(`// Code generated by cmd/gen-presets. DO NOT EDIT.
//
// The source of truth is the JSON documents in assets/presets, read through
// assets.List. Regenerate with: just gen-presets

/** One built-in sound the engine can play. */
export interface SoundPreset {
  /** What the engine resolves the sound by: the document's filename stem. */
  readonly id: string;
  /** The document's own "name" field, which is what a picker shows. */
  readonly label: string;
  /** The MIDI note the preset was authored at. */
  readonly note: number;
}

export const SOUND_PRESETS: readonly SoundPreset[] = [
`)

	for _, entry := range listed {
		b.WriteString("  { id: " + quote(entry.ID) +
			", label: " + quote(entry.Name) +
			", note: " + strconv.Itoa(entry.Note) + " },\n")
	}

	b.WriteString("] as const;\n\n")

	b.WriteString(`/**
 * The sound the engine falls back to, and what the picker starts on. It is the
 * same fallback assets.Preset applies to an empty id, so the two ends of the
 * bridge cannot disagree about which sound "none chosen" means.
 */
export const DEFAULT_SOUND_PRESET_ID = ` + quote(assets.DefaultID) + `;
`)

	return []byte(b.String()), nil
}

// quote emits a TypeScript string literal the way prettier would, so the
// generated file is already formatted and needs no ignore rule anywhere.
func quote(value string) string {
	if strings.Contains(value, `"`) && !strings.Contains(value, "'") {
		return "'" + strings.ReplaceAll(value, `\`, `\\`) + "'"
	}

	return strconv.Quote(value)
}
