package pack_test

import (
	"math"
	"testing"

	"github.com/cwbudde/algo-glockenspiel/internal/pack"
)

// TestFitLog2RecoversTheModelsOwnLaw is the calibration: data generated by
// exactly the law the model applies must come back as beta = 1 with no scatter,
// under either line. If this drifts, every exponent the report prints is
// measured against the wrong zero.
func TestFitLog2RecoversTheModelsOwnLaw(t *testing.T) {
	notes := []int{84, 88, 92, 96, 100, 103}
	decays := make([]float64, len(notes))

	// decay = 641 ms at note 84, divided by the transposition ratio.
	for i, note := range notes {
		decays[i] = 641 / math.Pow(2, float64(note-84)/12)
	}

	fit, ok := pack.FitLog2(notes, decays)
	if !ok {
		t.Fatal("a six-point regression was refused")
	}

	if math.Abs(fit.Exponent()-1) > 1e-9 {
		t.Errorf("beta = %.9f, want exactly 1 for the model's own law", fit.Exponent())
	}

	if fit.ResidualSD > 1e-9 || fit.PinnedSD > 1e-9 {
		t.Errorf("scatter %.9f fitted / %.9f pinned, want none: the data is the law exactly",
			fit.ResidualSD, fit.PinnedSD)
	}
}

// TestFitLog2SeparatesSlopeFromScatter is the distinction the whole report
// turns on. A fitted exponent can only remove the part of the spread that is a
// function of pitch; what is left is bar-to-bar variation, and no key-tracking
// law reaches it.
func TestFitLog2SeparatesSlopeFromScatter(t *testing.T) {
	notes := []int{84, 86, 88, 90, 92, 94, 96, 98}

	// A half-life that falls at half the model's rate -- beta = 0.5 -- with half
	// an octave of bar-to-bar noise on top.
	//
	// The noise pattern is chosen orthogonal to pitch: it sums to zero and so
	// does its product with the centred note, so it perturbs neither the slope
	// nor the intercept and lands entirely in the residual. A plain alternating
	// pattern is *not* orthogonal over an even grid -- it drags beta from 0.50
	// to 0.21 -- which is worth knowing, because it is what bar-to-bar variation
	// correlated with pitch would do to the real measurement.
	pattern := []float64{+1, -1, -1, +1, +1, -1, -1, +1}
	decays := make([]float64, len(notes))

	for i, note := range notes {
		decays[i] = 641 / math.Pow(2, 0.5*float64(note-84)/12) * math.Pow(2, 0.5*pattern[i])
	}

	fit, ok := pack.FitLog2(notes, decays)
	if !ok {
		t.Fatal("regression refused")
	}

	// The alternating term is orthogonal to the pitch trend over a symmetric
	// grid, so the slope survives it.
	if math.Abs(fit.Exponent()-0.5) > 0.05 {
		t.Errorf("beta = %.3f, want about 0.5", fit.Exponent())
	}

	// The scatter it leaves is the factor of two, half an octave either side.
	if math.Abs(fit.ResidualSD-0.5) > 0.05 {
		t.Errorf("residual scatter %.3f octaves, want about 0.5 -- the factor of two that is not pitch",
			fit.ResidualSD)
	}

	// And the model's own law leaves more, because it has the slope wrong too.
	if fit.PinnedSD <= fit.ResidualSD {
		t.Errorf("the model's law leaves %.3f octaves against the fitted line's %.3f; "+
			"a wrong slope cannot leave less", fit.PinnedSD, fit.ResidualSD)
	}
}

// TestFitLog2RefusesTooFewPoints keeps the report from claiming a scatter of
// zero because two points define a line.
func TestFitLog2RefusesTooFewPoints(t *testing.T) {
	if _, ok := pack.FitLog2([]int{84, 96}, []float64{600, 300}); ok {
		t.Error("a two-point regression was accepted, and it can only report no scatter")
	}

	if _, ok := pack.FitLog2([]int{84, 90, 96}, []float64{600, 0, 300}); ok {
		t.Error("a non-positive decay was accepted into a log regression")
	}
}
