package pack_test

import (
	"fmt"
	"math"
	"strings"
	"testing"

	"github.com/cwbudde/algo-glockenspiel/internal/pack"
)

// TestFitLog2RecoversTheModelsOwnLaw is the calibration: data generated by
// exactly the law the model applies must come back as beta = 1 with no scatter,
// under either line. If this drifts, every exponent the report prints is
// measured against the wrong zero.
func TestFitLog2RecoversTheModelsOwnLaw(t *testing.T) {
	notes := []int{84, 88, 92, 96, 100, 103}
	decays := make([]float64, len(notes))

	// decay = 641 ms at note 84, divided by the transposition ratio.
	for i, note := range notes {
		decays[i] = 641 / math.Pow(2, float64(note-84)/12)
	}

	fit, ok := pack.FitLog2(notes, decays)
	if !ok {
		t.Fatal("a six-point regression was refused")
	}

	if math.Abs(fit.Exponent()-1) > 1e-9 {
		t.Errorf("beta = %.9f, want exactly 1 for the model's own law", fit.Exponent())
	}

	if fit.ResidualSD > 1e-9 || fit.PinnedSD > 1e-9 {
		t.Errorf("scatter %.9f fitted / %.9f pinned, want none: the data is the law exactly",
			fit.ResidualSD, fit.PinnedSD)
	}
}

// TestFitLog2SeparatesSlopeFromScatter is the distinction the whole report
// turns on. A fitted exponent can only remove the part of the spread that is a
// function of pitch; what is left is bar-to-bar variation, and no key-tracking
// law reaches it.
func TestFitLog2SeparatesSlopeFromScatter(t *testing.T) {
	notes := []int{84, 86, 88, 90, 92, 94, 96, 98}

	// A half-life that falls at half the model's rate -- beta = 0.5 -- with half
	// an octave of bar-to-bar noise on top.
	//
	// The noise pattern is chosen orthogonal to pitch: it sums to zero and so
	// does its product with the centred note, so it perturbs neither the slope
	// nor the intercept and lands entirely in the residual. A plain alternating
	// pattern is *not* orthogonal over an even grid -- it drags beta from 0.50
	// to 0.21 -- which is worth knowing, because it is what bar-to-bar variation
	// correlated with pitch would do to the real measurement.
	pattern := []float64{+1, -1, -1, +1, +1, -1, -1, +1}
	decays := make([]float64, len(notes))

	for i, note := range notes {
		decays[i] = 641 / math.Pow(2, 0.5*float64(note-84)/12) * math.Pow(2, 0.5*pattern[i])
	}

	fit, ok := pack.FitLog2(notes, decays)
	if !ok {
		t.Fatal("regression refused")
	}

	// The alternating term is orthogonal to the pitch trend over a symmetric
	// grid, so the slope survives it.
	if math.Abs(fit.Exponent()-0.5) > 0.05 {
		t.Errorf("beta = %.3f, want about 0.5", fit.Exponent())
	}

	// The scatter it leaves is the factor of two, half an octave either side.
	if math.Abs(fit.ResidualSD-0.5) > 0.05 {
		t.Errorf("residual scatter %.3f octaves, want about 0.5 -- the factor of two that is not pitch",
			fit.ResidualSD)
	}

	// And the model's own law leaves more, because it has the slope wrong too.
	if fit.PinnedSD <= fit.ResidualSD {
		t.Errorf("the model's law leaves %.3f octaves against the fitted line's %.3f; "+
			"a wrong slope cannot leave less", fit.PinnedSD, fit.ResidualSD)
	}
}

// TestFitLog2RefusesTooFewPoints keeps the report from claiming a scatter of
// zero because two points define a line.
func TestFitLog2RefusesTooFewPoints(t *testing.T) {
	if _, ok := pack.FitLog2([]int{84, 96}, []float64{600, 300}); ok {
		t.Error("a two-point regression was accepted, and it can only report no scatter")
	}

	if _, ok := pack.FitLog2([]int{84, 90, 96}, []float64{600, 0, 300}); ok {
		t.Error("a non-positive decay was accepted into a log regression")
	}
}

// TestRatioClustersFollowThePartialNotTheIndex is the whole reason clustering
// exists. The fits hold different numbers of modes at different notes -- g6
// came back with four and ds6 with nine -- so a mode index is a position in one
// note's list, and two notes' "mode 2" are routinely different partials.
//
// The fixture is that failure exactly: three notes whose second partial sits at
// the free-free ratio, one of which additionally found a weak partial below it,
// pushing everything after it down one index.
func TestRatioClustersFollowThePartialNotTheIndex(t *testing.T) {
	rows := []pack.ModeRow{
		// c6: fundamental, free-free, and a high partial.
		{Note: 84, Index: 0, Ratio: 1.00, DecayMs: 800},
		{Note: 84, Index: 1, Ratio: 2.77, DecayMs: 400},
		{Note: 84, Index: 2, Ratio: 5.36, DecayMs: 200},

		// d6: the same three partials, at the same indices.
		{Note: 86, Index: 0, Ratio: 1.01, DecayMs: 780},
		{Note: 86, Index: 1, Ratio: 2.76, DecayMs: 390},
		{Note: 86, Index: 2, Ratio: 5.33, DecayMs: 195},

		// e6: an extra weak partial at 1.9 shifts every later index by one, so
		// its free-free partial is "mode 2" where the others' is "mode 1".
		{Note: 88, Index: 0, Ratio: 1.00, DecayMs: 760},
		{Note: 88, Index: 1, Ratio: 1.90, DecayMs: 500},
		{Note: 88, Index: 2, Ratio: 2.74, DecayMs: 380},
		{Note: 88, Index: 3, Ratio: 5.35, DecayMs: 190},
	}

	clusters := pack.ByRatioCluster(rows)

	want := []struct {
		ratio float64
		notes int
	}{
		{1.00, 3}, // the fundamental, at every note
		{1.90, 1}, // e6's extra partial, alone
		{2.76, 3}, // the free-free ratio, at every note despite the index shift
		{5.35, 3},
	}

	if len(clusters) != len(want) {
		got := make([]string, 0, len(clusters))
		for _, cluster := range clusters {
			got = append(got, fmt.Sprintf("%.2f x%d", cluster.Rows[0].Ratio, cluster.Notes))
		}

		t.Fatalf("clustered into %d groups (%s), want %d", len(clusters), strings.Join(got, ", "), len(want))
	}

	for i, expect := range want {
		mean := 0.0
		for _, row := range clusters[i].Rows {
			mean += row.Ratio
		}

		mean /= float64(len(clusters[i].Rows))

		if math.Abs(mean-expect.ratio) > 0.05 {
			t.Errorf("cluster %d sits at %.3f, want about %.2f", i, mean, expect.ratio)
		}

		if clusters[i].Notes != expect.notes {
			t.Errorf("cluster %d spans %d notes, want %d", i, clusters[i].Notes, expect.notes)
		}
	}

	// The index grouping the clustering replaces gets this wrong, and that is
	// the claim rather than a bit of colour: mode 1 pools e6's 1.90 partial
	// with the other two notes' free-free partial, and the mixture is what a
	// regression would have called key tracking.
	_, byIndex := pack.ByModeIndex(rows)

	spread := 0.0
	for _, row := range byIndex[1] {
		if delta := math.Abs(row.Ratio - 2.76); delta > spread {
			spread = delta
		}
	}

	if spread < 0.5 {
		t.Errorf("mode index 1 holds ratios within %.2f of the free-free partial, so this "+
			"fixture no longer exercises the failure clustering exists to fix", spread)
	}
}
