// Command gen-fit-schema writes the TypeScript mirror of internal/fitschema:
// the fit request's field limits and defaults, the optimizer, metric,
// CMA-ES and mayfly name lists, and the model's bounds keys.
//
// Before this table existed, its TypeScript counterpart -- FIT_LIMITS,
// DEFAULT_FIT_REQUEST, OPTIMIZER_NAMES and the rest, in web/src/api/types.ts
// -- was transcribed by hand from three Go sources that were themselves
// starting to disagree: internal/server's limits and internal/browserfit's
// were not the same numbers. Generating it, and failing CI on a diff,
// follows the precedent cmd/gen-mayfly-tuning and cmd/gen-presets already
// set for exactly this problem.
//
// Usage:
//
//	go run ./cmd/gen-fit-schema            # write the file
//	go run ./cmd/gen-fit-schema --check    # fail if it is out of date
package main

import (
	"bytes"
	"flag"
	"fmt"
	"math"
	"os"
	"strconv"
	"strings"

	"github.com/cwbudde/algo-glockenspiel/internal/fitschema"
)

const typescriptPath = "web/src/api/fitSchema.generated.ts"

func main() {
	check := flag.Bool("check", false, "verify the generated file is up to date instead of writing it")

	flag.Parse()

	generated := renderTypeScript()

	if !*check {
		if err := os.WriteFile(typescriptPath, generated, 0o644); err != nil { //nolint:gosec // generated source, not a secret
			fail(err)
		}

		return
	}

	current, err := os.ReadFile(typescriptPath)
	if err != nil {
		fail(fmt.Errorf("%w: run `just gen-fit-schema`", err))
	}

	if !bytes.Equal(current, generated) {
		fail(fmt.Errorf("%s is out of date: run `just gen-fit-schema`", typescriptPath))
	}
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "gen-fit-schema: %v\n", err)
	os.Exit(1)
}

// renderTypeScript builds the browser's copy of the schema, field for field
// and list for list, from internal/fitschema.
func renderTypeScript() []byte {
	var b strings.Builder

	b.WriteString(`// Code generated by cmd/gen-fit-schema. DO NOT EDIT.
//
// The source of truth is internal/fitschema. Regenerate with: just gen-fit-schema

`)

	writeNameList(&b, "MetricName", "METRIC_NAMES",
		"optimizer.ParseMetric's vocabulary: the three composite profiles, then the single-term legacy metrics.",
		fitschema.MetricNames())
	writeNameList(&b, "OptimizerName", "OPTIMIZER_NAMES",
		"selectOptimizer's vocabulary.", fitschema.OptimizerNames())
	writeNameList(&b, "CmaesCovariance", "CMAES_COVARIANCES",
		"CMAESOptimizer.resolve's vocabulary: the covariance it learns.", fitschema.CMAESCovariances())
	writeNameList(&b, "MayflyVariant", "MAYFLY_VARIANTS",
		"MayflyOptimizer.Validate's vocabulary.", fitschema.MayflyVariants())
	writeNameList(&b, "MayflyPreset", "MAYFLY_PRESETS",
		"mayfly.ConfigPreset's vocabulary, from config_loader.go upstream. A preset "+
			"already chooses a dialect, so the engine refuses a preset and an explicit "+
			"variant together; the form sends one or the other, never both.",
		fitschema.MayflyPresets())
	writeNameList(&b, "MayflySelection", "MAYFLY_SELECTIONS",
		"The `selection` knob's vocabulary: how crossover pairs its parents.", fitschema.MayflySelections())

	writeFitLimits(&b)
	writeDefaultFitRequest(&b)
	writeBounds(&b)
	writeMayflyDefaultReportEvery(&b)

	return []byte(b.String())
}

// writeNameList emits one vocabulary as a readonly tuple, the derived union
// type, and the plain readonly array alias every one of them used to be
// duplicated as (METRIC_NAMES and OPTIMIZER_NAMES were `readonly X[]`, not
// `as const`, in the hand-written file; both forms are produced here so
// every import site keeps compiling unchanged).
func writeNameList(b *strings.Builder, typeName, constName, doc string, values []string) {
	fmt.Fprintf(b, "/** %s */\n", doc)
	writeArrayConst(b, constName, values)
	b.WriteString("\n")

	fmt.Fprintf(b, "/** Derived from %s. */\n", constName)
	fmt.Fprintf(b, "export type %s = (typeof %s)[number];\n\n", typeName, constName)
}

// writeArrayConst emits `export const <name> = [...] as const;`, on one line
// when it fits inside prettier's 80-column default and one item per line
// otherwise -- prettier's own rule for an array literal, which does not get
// the "keep it however the source broke it" treatment an object literal
// does. Replicating the rule here, rather than shelling out to prettier, is
// what keeps this generator's raw output already the form `npx prettier
// --check` accepts, exactly as cmd/gen-mayfly-tuning's does.
func writeArrayConst(b *strings.Builder, name string, items []string) {
	quoted := make([]string, len(items))
	for i, item := range items {
		quoted[i] = quote(item)
	}

	const printWidth = 80

	oneLine := fmt.Sprintf("export const %s = [%s] as const;", name, strings.Join(quoted, ", "))
	if len(oneLine) <= printWidth {
		b.WriteString(oneLine + "\n")

		return
	}

	fmt.Fprintf(b, "export const %s = [\n", name)

	for _, item := range quoted {
		b.WriteString("  " + item + ",\n")
	}

	b.WriteString("] as const;\n")
}

// writeFitLimits emits FIT_LIMITS: every field the table holds to a numeric
// range, keyed by its FIT_LIMITS spelling.
func writeFitLimits(b *strings.Builder) {
	b.WriteString(`/**
 * The server's own limits, from internal/fitschema. They are mirrored here
 * so a value that cannot be accepted is refused before it is uploaded, not
 * after.
 */
export const FIT_LIMITS = {
`)

	for _, field := range fitschema.Fields() {
		if !field.HasLimit {
			continue
		}

		key := field.Key
		if field.LimitKey != "" {
			key = field.LimitKey
		}

		if field.Kind == fitschema.KindBytes {
			fmt.Fprintf(b, "  %s: %s,\n", key, number(field.Max))

			continue
		}

		fmt.Fprintf(b, "  %s: { min: %s, max: %s },\n", key, number(field.Min), number(field.Max))
	}

	b.WriteString("} as const;\n\n")
}

// writeDefaultFitRequest emits DEFAULT_FIT_REQUEST: every request field that
// carries a default, in FitRequestFields's own key spelling.
//
// It is deliberately not typed against FitRequestFields here: that interface
// lives in web/src/api/types.ts, and this file must not import from the file
// that imports it, on pain of a cycle. `as const` gives every property its
// own literal type instead -- "simple" rather than string -- which is what
// lets types.ts assign this value to a FitRequestFields-typed export without
// widening a single field back to string or number.
func writeDefaultFitRequest(b *strings.Builder) {
	b.WriteString(`/**
 * defaultFitRequest's values, from internal/fitschema, so a preset fitted
 * from the browser and one fitted from the terminal are the same fit.
 */
export const DEFAULT_FIT_REQUEST = {
`)

	for _, field := range fitschema.Fields() {
		if !field.InRequest || !field.HasDefault {
			continue
		}

		fmt.Fprintf(b, "  %s: %s,\n", field.Key, defaultLiteral(field))
	}

	b.WriteString("} as const;\n\n")
}

// defaultLiteral renders one field's default the way its Kind travels on the
// wire: a duration as its Go-formatted string, a seed as a quoted decimal,
// everything else as its own JSON literal.
func defaultLiteral(field fitschema.Field) string {
	switch field.Kind {
	case fitschema.KindDuration:
		return quote(fitschema.DefaultDuration(field.Key).String())
	case fitschema.KindSeed:
		return quote(strconv.FormatInt(fitschema.DefaultInt64(field.Key), 10))
	case fitschema.KindBool:
		return strconv.FormatBool(fitschema.DefaultBool(field.Key))
	case fitschema.KindEnum:
		return quote(fitschema.DefaultString(field.Key))
	case fitschema.KindInt, fitschema.KindSafeInt:
		return strconv.Itoa(fitschema.DefaultInt(field.Key))
	case fitschema.KindFloat:
		return number(fitschema.DefaultFloat(field.Key))
	default:
		panic(fmt.Sprintf("gen-fit-schema: field %q has no default rendering for kind %q", field.Key, field.Kind))
	}
}

// writeBounds emits the model bounds vocabulary: the accepted keys, which of
// them are log-encoded, the model's own domain per key, and the default
// search box.
//
// None of this is typed against BoundsKey, BoundsRange or BoundsDocument
// here: all three are declared in web/src/api/types.ts, which imports this
// file, so this file cannot import them back without a cycle. types.ts
// re-exports every value below through a wrapper that adds the annotation,
// which is also where the runtime keys are checked against the interface's
// own, by TypeScript itself refusing to compile a mismatch.
func writeBounds(b *strings.Builder) {
	keys := fitschema.BoundsKeys()

	b.WriteString("/** The keys a bounds document may carry, in the order the docs list them. */\n")
	writeArrayConst(b, "BOUNDS_KEYS", keys)
	b.WriteString("\n")

	b.WriteString(`/**
 * The dimensions the codec log-encodes. Their bounds must stay strictly
 * above zero: log(0) is not a number the unit-cube encoding can take, and
 * the server answers a non-positive one with a 400.
 */
`)
	writeArrayConst(b, "LOG_ENCODED_BOUNDS_KEYS", fitschema.LogEncodedBoundsKeys())
	b.WriteString("\n")

	writeBoundsTable(b, "MODEL_BOUNDS_LIMITS",
		`The range model.ValidateBarParams holds each dimension to. `+
			`DecodeParamBounds in internal/optimizer/boundsfile.go rejects a supplied `+
			`range that leaves this box, and for a good reason: every candidate drawn `+
			`from it would fail validation and score +Inf, so the fit would burn its `+
			`whole budget to produce nothing.`,
		keys, fitschema.ModelBoundsLimits())

	writeBoundsTable(b, "DEFAULT_PARAM_BOUNDS",
		`optimizer.DefaultParamBounds, shown as the placeholder for each field. `+
			`Two of these are narrowed per fit before the search starts, without a `+
			`document: frequency to half the reference's fundamental up to 0.45 of its `+
			`sample rate, and decay_ms to what a preset at the starting preset's note `+
			`may carry. A document replaces the whole box, so a frequency key in one is `+
			`the box that runs.`,
		keys, fitschema.DefaultParamBounds())
}

func writeBoundsTable(b *strings.Builder, name, doc string, keys []string, values map[string]fitschema.Range) {
	fmt.Fprintf(b, "/** %s */\n", doc)
	fmt.Fprintf(b, "export const %s = {\n", name)

	for _, key := range keys {
		r := values[key]
		fmt.Fprintf(b, "  %s: [%s, %s] as const,\n", key, number(r.Min), number(r.Max))
	}

	b.WriteString("} as const;\n\n")
}

// writeMayflyDefaultReportEvery emits the progress cadence a mayfly fit gets
// when nobody chooses one, mirroring fitschema.DefaultMayflyReportEvery.
func writeMayflyDefaultReportEvery(b *strings.Builder) {
	fmt.Fprintf(b, `/**
 * The progress cadence a Mayfly fit gets when nobody chooses one, mirroring
 * fitschema.DefaultMayflyReportEvery.
 *
 * A Mayfly iteration is a whole generation -- population, offspring, mutants
 * and elites, measured at roughly 47.7 objective evaluations at a population
 * of ten -- while a simple iteration is about one evaluation. The simple
 * backend's own default cadence would therefore mean "after roughly five
 * hundred renders" for Mayfly, long enough that a default time budget ends
 * before the first report and the cost curve stays empty for the whole run.
 */
export const MAYFLY_DEFAULT_REPORT_EVERY = %d;
`, fitschema.DefaultMayflyReportEvery)
}

// quote emits a TypeScript string literal the way prettier would, preferring
// double quotes and switching to single ones only when that means fewer
// escapes.
func quote(value string) string {
	if strings.Contains(value, `"`) && !strings.Contains(value, "'") {
		return "'" + strings.ReplaceAll(value, `\`, `\\`) + "'"
	}

	return strconv.Quote(value)
}

// number formats in fixed notation, so the generated file reads like
// something a person wrote instead of switching to scientific notation the
// moment a byte count crosses seven digits -- 'g' does that at 1.6777216e+07
// -- and spells the JS safe-integer bound the way TypeScript itself would.
func number(value float64) string {
	switch {
	case math.IsInf(value, 1), value == fitschema.JSMaxSafeInteger:
		return "Number.MAX_SAFE_INTEGER"
	case math.IsInf(value, -1), value == -fitschema.JSMaxSafeInteger:
		return "Number.MIN_SAFE_INTEGER"
	default:
		return strconv.FormatFloat(value, 'f', -1, 64)
	}
}
