// Command gen-mayfly-tuning writes the TypeScript mirror of the Mayfly tuning
// knob table.
//
// The table exists once, in optimizer.MayflyTuningFields, and the browser needs
// it to render a form that shows only the knobs the selected dialect owns.
// Neither of the two obvious ways of getting it there works: serving it from
// the fit API is dead on GitHub Pages, which is exactly where the WASM path
// runs, and exporting it from the WASM module is too late, because the form
// renders before the module loads.
//
// So it is generated, and CI regenerates it and fails on a diff. The repo
// already does this for the wood textures (web/package.json's wood:generate and
// wood:check --check), and this follows that pattern.
//
// Usage:
//
//	go run ./cmd/gen-mayfly-tuning            # write the file
//	go run ./cmd/gen-mayfly-tuning --check    # fail if it is out of date
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/cwbudde/algo-glockenspiel/internal/optimizer"
)

// The knob table has two mirrors, both generated from the same Go table and
// both verified by --check: one the browser form reads, and one a person reads.
const (
	typescriptPath = "web/src/api/mayflyTuning.generated.ts"
	markdownPath   = "docs/mayfly-tuning.md"
)

func main() {
	check := flag.Bool("check", false, "verify the generated files are up to date instead of writing them")

	flag.Parse()

	outputs := map[string][]byte{
		typescriptPath: renderTypeScript(),
		markdownPath:   renderMarkdown(),
	}

	for path, generated := range outputs {
		if err := emit(path, generated, *check); err != nil {
			fail(err)
		}
	}
}

func emit(path string, generated []byte, check bool) error {
	if !check {
		return os.WriteFile(path, generated, 0o644) //nolint:gosec // generated source, not a secret
	}

	current, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("%w: run `just gen-mayfly-tuning`", err)
	}

	if !bytes.Equal(current, generated) {
		return fmt.Errorf("%s is out of date: run `just gen-mayfly-tuning`", path)
	}

	return nil
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "gen-mayfly-tuning: %v\n", err)
	os.Exit(1)
}

// renderTypeScript builds the browser's copy. The shape mirrors
// optimizer.MayflyTuningField so a reader can hold one mental model of the
// table across both languages.
func renderTypeScript() []byte {
	var b strings.Builder

	b.WriteString(`// Code generated by cmd/gen-mayfly-tuning. DO NOT EDIT.
//
// The source of truth is optimizer.MayflyTuningFields in
// internal/optimizer/tuningfile.go. Regenerate with: just gen-mayfly-tuning

/** One tunable Mayfly knob. */
export interface MayflyTuningField {
  /** The JSON key, which is mayfly's own config field name. */
  readonly key: string;
  readonly label: string;
  readonly kind: "float" | "int" | "enum" | "bool";
  /**
   * The dialect that owns the knob, or "" when every dialect has it. A form
   * shows a knob only when this is "" or matches the selected variant.
   */
  readonly variant: string;
  readonly min?: number;
  readonly max?: number;
  readonly minExclusive?: boolean;
  readonly maxExclusive?: boolean;
  readonly options?: readonly string[];
  readonly help: string;
}

export const MAYFLY_TUNING_FIELDS: readonly MayflyTuningField[] = [
`)

	for _, field := range optimizer.MayflyTuningFields() {
		b.WriteString("  {\n")
		b.WriteString("    key: " + quote(field.Key) + ",\n")
		b.WriteString("    label: " + quote(field.Label) + ",\n")
		b.WriteString("    kind: " + quote(field.Kind) + ",\n")
		b.WriteString("    variant: " + quote(field.Variant) + ",\n")

		if field.Min != nil {
			b.WriteString("    min: " + number(*field.Min) + ",\n")
		}

		if field.Max != nil {
			b.WriteString("    max: " + number(*field.Max) + ",\n")
		}

		if field.MinExclusive {
			b.WriteString("    minExclusive: true,\n")
		}

		if field.MaxExclusive {
			b.WriteString("    maxExclusive: true,\n")
		}

		if len(field.Options) > 0 {
			quoted := make([]string, len(field.Options))
			for i, option := range field.Options {
				quoted[i] = quote(option)
			}

			b.WriteString("    options: [" + strings.Join(quoted, ", ") + "],\n")
		}

		b.WriteString("    help: " + quote(field.Help) + ",\n")
		b.WriteString("  },\n")
	}

	b.WriteString("] as const;\n\n")

	b.WriteString(`/** The knobs a dialect can set: the shared ones plus its own. */
export function mayflyTuningFieldsFor(
  variant: string,
): readonly MayflyTuningField[] {
  return MAYFLY_TUNING_FIELDS.filter(
    (field) => field.variant === "" || field.variant === variant,
  );
}
`)

	return []byte(b.String())
}

func quote(value string) string {
	return strconv.Quote(value)
}

// number formats without an exponent where it can, so the generated file reads
// like something a person wrote.
func number(value float64) string {
	return strconv.FormatFloat(value, 'g', -1, 64)
}

// renderMarkdown builds the documentation table. It is generated for the same
// reason the TypeScript is: fifty-odd keys transcribed by hand would be wrong
// within a release, and a documented range that disagrees with the validator is
// worse than no documentation at all.
func renderMarkdown() []byte {
	var b strings.Builder

	b.WriteString(`<!-- Code generated by cmd/gen-mayfly-tuning. DO NOT EDIT. -->
<!-- Source: optimizer.MayflyTuningFields in internal/optimizer/tuningfile.go -->
<!-- Regenerate with: just gen-mayfly-tuning -->

# Mayfly tuning keys

Every key below is optional. An omitted key keeps whatever the dialect -- or the
preset -- already chose, which is what makes an empty document a no-op. Unknown
keys are rejected rather than ignored, because a misspelled knob that was
silently dropped would run a fit at the default while you believed you had
tuned it.

Keys marked with a dialect apply only to that dialect. Passing one to a
different dialect is an error, not a no-op: mayfly ignores the fields of
variants it is not running, so the value would land on the configuration,
change nothing, and leave you believing the run was tuned.

See [optimizer.md](optimizer.md) for how the document fits into a run.

`)

	sections := []struct {
		variant string
		title   string
	}{
		{"", "Shared"},
		{"desma", "DESMA"},
		{"olce", "OLCE-MA"},
		{"eobbma", "EOBBMA"},
		{"gsasma", "GSASMA"},
		{"mpma", "MPMA"},
		{"aoblmoa", "AOBLMOA"},
	}

	fields := optimizer.MayflyTuningFields()

	for _, section := range sections {
		rows := make([]optimizer.MayflyTuningField, 0, len(fields))

		for _, field := range fields {
			if field.Variant == section.variant {
				rows = append(rows, field)
			}
		}

		if len(rows) == 0 {
			continue
		}

		b.WriteString("## " + section.title + "\n\n")
		b.WriteString("| Key | Type | Range | Description |\n")
		b.WriteString("| --- | --- | --- | --- |\n")

		for _, field := range rows {
			b.WriteString("| `" + field.Key + "` | " + field.Kind + " | " +
				markdownRange(field) + " | " + escapePipes(field.Help) + " |\n")
		}

		b.WriteString("\n")
	}

	return []byte(b.String())
}

// markdownRange renders a field's constraint the way the validator applies it.
func markdownRange(field optimizer.MayflyTuningField) string {
	if len(field.Options) > 0 {
		quoted := make([]string, len(field.Options))
		for i, option := range field.Options {
			quoted[i] = "`" + option + "`"
		}

		return strings.Join(quoted, ", ")
	}

	switch {
	case field.Min != nil && field.Max != nil:
		open, close := "[", "]"
		if field.MinExclusive {
			open = "("
		}

		if field.MaxExclusive {
			close = ")"
		}

		return open + number(*field.Min) + ", " + number(*field.Max) + close

	case field.Min != nil:
		if field.MinExclusive {
			return "> " + number(*field.Min)
		}

		return ">= " + number(*field.Min)

	case field.Max != nil:
		if field.MaxExclusive {
			return "< " + number(*field.Max)
		}

		return "<= " + number(*field.Max)
	}

	if field.Kind == "bool" {
		return "true, false"
	}

	return "any finite"
}

func escapePipes(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}
