name: test-wasm

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go-Version
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Build WASM demo
        run: ./scripts/build-wasm.sh
